#Author
title: gwfp的驿站
author: gwfp

#Build setting
        
#Directory
source_dir: source

#paginate
paginate: 10
paginate_path: "/blog/page:num/"

#Markdown
markdown: kramdown

#RSS
name: gwfp's Post Station
description: 心仪的东西到手后，才真正的要开始奋斗了．
url: https://gwfp.github.io

#Plugins
gems: [jekyll-paginate]
