#Author
title: gwfp的驿站
author: gwfp

#Build setting
        
#Directory
source_dir: source

#paginate
paginate: 5
paginate_path: "/blog/page:num/"

#Markdown
markdown: kramdown

#RSS


#Plugins
gems: [jekyll-paginate]
